import {
  generateRandomWinningNumbers,
  generateAlgorithmicWinningNumbers,
  evaluateTicketMatch,
  calculateTotalPrizePool,
  simulateDraw,
  DrawTicket,
} from './draw-engine';

function runDrawEngineTests() {
  console.log('--- STARTING DRAW & PRIZE ENGINE UNIT TESTS ---');
  let passed = 0;
  let failed = 0;

  function assert(condition: boolean, testName: string) {
    if (condition) {
      console.log(`✓ [PASS] ${testName}`);
      passed++;
    } else {
      console.error(`✗ [FAIL] ${testName}`);
      failed++;
    }
  }

  // 1. Deterministic Number Generation Tests
  const seed1 = 'test-seed-2026';
  const numsA = generateRandomWinningNumbers(seed1);
  const numsB = generateRandomWinningNumbers(seed1);

  assert(numsA.length === 5, 'Generates exactly 5 winning numbers');
  assert(numsA.every((n) => n >= 1 && n <= 45), 'All winning numbers are within 1..45');
  assert(new Set(numsA).size === 5, 'All 5 winning numbers are unique');
  assert(JSON.stringify(numsA) === JSON.stringify(numsB), 'Deterministic seed yields identical numbers');

  // 2. Ticket Match Evaluation Tests
  const winning = [10, 20, 30, 40, 45];
  assert(evaluateTicketMatch([10, 20, 30, 40, 45], winning).matchCount === 5, '5-number match detected');
  assert(evaluateTicketMatch([10, 20, 30, 40, 45], winning).tier === 'tier_5_match', '5-number match yields tier_5_match');

  assert(evaluateTicketMatch([10, 20, 30, 40, 12], winning).matchCount === 4, '4-number match detected');
  assert(evaluateTicketMatch([10, 20, 30, 40, 12], winning).tier === 'tier_4_match', '4-number match yields tier_4_match');

  assert(evaluateTicketMatch([10, 20, 30, 11, 12], winning).matchCount === 3, '3-number match detected');
  assert(evaluateTicketMatch([10, 20, 30, 11, 12], winning).tier === 'tier_3_match', '3-number match yields tier_3_match');

  assert(evaluateTicketMatch([10, 20, 1, 2, 3], winning).matchCount === 2, '2-number match detected');
  assert(evaluateTicketMatch([10, 20, 1, 2, 3], winning).tier === 'none', '2-number match yields no tier');

  // 3. Prize Pool Calculation Tests
  const pool100 = calculateTotalPrizePool(100, 29);
  assert(pool100 === 5000, 'Minimum prize pool floor is $5,000');

  const pool1000 = calculateTotalPrizePool(1000, 29);
  assert(pool1000 === 14500, '1000 subscribers * $29 * 50% = $14,500 prize pool');

  // 4. Draw Simulation & Tier Splits Test (Multiple Winners)
  // Use actual winning numbers generated by seed1 to build tickets
  const w = numsA; // e.g. [w0, w1, w2, w3, w4]
  const nonMatch = 1; // Any number not in w

  const tickets: DrawTicket[] = [
    // 5-match winner
    { userId: 'u1', numbers: [w[0], w[1], w[2], w[3], w[4]], scoreIds: ['s1'] },
    // Two 4-match winners
    { userId: 'u2', numbers: [w[0], w[1], w[2], w[3], nonMatch], scoreIds: ['s2'] },
    { userId: 'u3', numbers: [w[0], w[1], w[2], w[3], nonMatch + 1], scoreIds: ['s3'] },
    // Three 3-match winners
    { userId: 'u4', numbers: [w[0], w[1], w[2], nonMatch, nonMatch + 1], scoreIds: ['s4'] },
    { userId: 'u5', numbers: [w[0], w[1], w[2], nonMatch + 2, nonMatch + 3], scoreIds: ['s5'] },
  ];

  const simResult = simulateDraw(tickets, 'random', seed1, 10000, 2000);

  assert(simResult.totalPrizePool === 10000, 'Total prize pool is $10,000');
  assert(simResult.tier5.totalTierPool === 6000, 'Tier 5 pool = 40% of $10k ($4000) + $2000 rollover = $6000');
  assert(simResult.tier4.totalTierPool === 3500, 'Tier 4 pool = 35% of $10k = $3500');
  assert(simResult.tier3.totalTierPool === 2500, 'Tier 3 pool = 25% of $10k = $2500');
  assert(simResult.tier5.winnerCount === 1, '1 Tier 5 winner identified');
  assert(simResult.tier4.winnerCount === 2, '2 Tier 4 winners identified');
  assert(simResult.tier4.prizePerWinner === 1750, 'Tier 4 pool ($3500) split equally between 2 winners = $1750 each');

  // 5. Jackpot Rollover Test (No Tier 5 Winners)
  const noTier5Tickets: DrawTicket[] = [
    { userId: 'u2', numbers: [w[0], w[1], w[2], w[3], nonMatch], scoreIds: ['s2'] },
  ];

  const simNo5 = simulateDraw(noTier5Tickets, 'random', seed1, 10000, 1500);
  assert(simNo5.tier5.winnerCount === 0, 'No Tier 5 winners in simulation');
  assert(simNo5.nextRollover === 5500, 'Entire Tier 5 pool ($4000 + $1500 = $5500) rolls over to next draw');
  assert(simNo5.tier4.winnerCount === 1, 'Tier 4 winner present in simulation');

  // 6. Algorithmic Weighted Selection Test
  const algoNums = generateAlgorithmicWinningNumbers(tickets, seed1);
  assert(algoNums.length === 5, 'Algorithmic mode generates 5 unique numbers');

  console.log(`--- DRAW ENGINE TEST RESULTS: ${passed} PASSED, ${failed} FAILED ---`);
  if (failed > 0) process.exit(1);
}

runDrawEngineTests();
